server:
  port: 8081

spring:
  session:
    timeout: 30m

clients:
  museum-api:
    base-url: http://localhost:8080
    connect-timeout-ms: 3000
    response-timeout: 10s
    max-in-memory: 256KB
    max-connections: 50

auth:
  username: admin1
  password: admin123
  service:
    url: http://localhost:8080
